name: Node checkout

on: [push]

jobs:
  node14:
    name: Run Build and Test Node 14
    runs-on: ubuntu-latest
    container: node:14
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: mypassword
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build
      - run: npm test
        env:
          JWT_SECRET: "super-secret-jwt"
          SECRET_SESSION: "super-secret-session"
          DB_CLIENT: "pg"
          DB_HOST: "postgres"
          DB_USER: "postgres"
          DB_PASS: "mypassword"
          DB_NAME: "postgres"

  node15:
    name: Run Build and Test Node 14
    runs-on: ubuntu-latest
    container: node:15
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: mypassword
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build
      - run: npm test
        env:
          JWT_SECRET: "super-secret-jwt"
          SECRET_SESSION: "super-secret-session"
          DB_CLIENT: "pg"
          DB_HOST: "postgres"
          DB_USER: "postgres"
          DB_PASS: "mypassword"
          DB_NAME: "postgres"
