name: Node checkout

on: [push]

jobs:
  build:
    name: Run Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        containers-node: ['node:14', 'node:15']
        
    container: ${{matrix.containers-node}}
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: mypassword
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
    steps:
      - uses: actions/checkout@v2
      
      - run: npm ci
      - run: npm run build
      - run: npm test
        env:
          JWT_SECRET: "super-secret-jwt"
          SECRET_SESSION: "super-secret-session"
          DB_CLIENT: "pg"
          DB_HOST: "postgres"
          DB_USER: "postgres"
          DB_PASS: "mypassword"
          DB_NAME: "postgres"
