name: Node checkout

on: [push]

jobs:
  build:
    name: Run Build and Test
    runs-on: ubuntu-latest
    container: node
    services:
      mysql: 
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: mypassword
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build
      - run: npm test
        env:
          JWT_SECRET: "super-secret-jwt"
          SECRET_SESSION: "super-secret-session"
          DB_CLIENT: "mysql2"
          DB_HOST: "mysql"
          DB_USER: "root"
          DB_PASS: "mypassword"
          DB_NAME: "db"
